### ISSUE TITLE
GitHub AST Viewer

### ISSUE THREAD

**Issue by lukehorvat** [stefanbuck/awesome-browser-extensions-for-github#10]
I made a Chrome extension that lets you view the abstract syntax tree of code on GitHub. It is still in early stages, but I think it has some potential educational value.

https://github.com/lukehorvat/github-ast-viewer

If you feel it is worthy of being on the list, let me know and I'll send you a PR. :smiley:

**Comment by stefanbuck** [comment]
Yes please, looks great!
