### ISSUE TITLE
How about adding PR Monitor?

### ISSUE THREAD

**Issue by fwouts** [stefanbuck/awesome-browser-extensions-for-github#130]
I built this extension, so this request is totally self-interested :)

![Screencast](https://github.com/fwouts/prmonitor/raw/master/screencasts/v0.5.1.gif)

https://github.com/fwouts/prmonitor

**Comment by stefanbuck** [comment]
Sorry for the delay. I somehow missed the notification. However, yes please sent a PR. PR Monitor looks really useful and this needs to be shared
