### ISSUE TITLE
"GitHub Plus" is now renamed "Enhanced GitHub"

### ISSUE THREAD

**Issue by gaojr** [stefanbuck/awesome-browser-extensions-for-github#132]
![](https://user-images.githubusercontent.com/18600387/67383227-672ce700-f5c1-11e9-91cb-ffd3d246dd32.png)

**Comment by stefanbuck** [comment]
Thanks, would you like to submit a PR?

**Comment by gaojr** [comment]
> Thanks, would you like to submit a PR?

Just saw your message , I've opened the PR #134
