### ISSUE TITLE
Collapse no longer maintained extensions

### ISSUE THREAD

**Issue by kidonng** [stefanbuck/awesome-browser-extensions-for-github#146]
First of all, thanks for making this awesome list!

I remember reading this list and finding many useful extensions that I still use every day (Refined GitHub, Octotree... to name a few) about 3 years ago. However, it's sad to see most of the extensions on this list is no longer maintained now (1 year with no updates is probably enough since GitHub frequently updates and "breaks" user-land extensions, I'm a contributor to Refined GitHub so I understand this well). I suggest hiding them in a collapsible list (using `<summary>`) and put them at the end of the document so people can save time visiting these extensions only to find they are no longer working.

An alternative solution is to put a "no longer maintained" or last update date label next to the extension name.

**Comment by stefanbuck** [comment]
You know what, I was thinking about something similar while fixing the alphabetical order of the list last week. My idea was to enrich the list with meta information like GitHub stars (if the extension is open source) or the last publish date. I like the idea of having a dedicated `no longer maintained` list. Would you like to submit a PR for this?

**Comment by stefanbuck** [comment]
First attempt to address this issue by turning this awesome list into a web page so you can filter and sort the list https://stefanbuck.com/awesome-browser-extensions-for-github.

Any feedback is appreciated

**Comment by darkred** [comment]
I love your work, and turning the list into a standalone page is a brilliant idea! 
And turning it into a two-column list, great! Thank you.

---

Two suggestions, please:

1. regarding the sorting options, I'd suggest changing their texts to the following
(based on how sorting options are in GitHub search pages, as they are quite sorter/simple strings):
    
    ```
    Most installs
    Fewest installs
    Most stars
    Fewest stars
    Recently updated
    Least recently updated
    ```

    Screenshots, for reference: 

    [Current sorting options](https://user-images.githubusercontent.com/723651/90542300-8e762580-e18c-11ea-9bbe-29d907addd12.jpg) and [GitHub search pages sorting options](https://user-images.githubusercontent.com/723651/90543522-7dc6af00-e18e-11ea-985d-519c8d8c825c.jpg)
    </details>


1. it would be great to have a **Dark theme** option.

**Comment by stefanbuck** [comment]
Thank you for the kind words. I’m going to rename the sorting options as you suggested, less wordy and overall much better. Regarding the dark mode, I’ll consider it but will take some time since I have other projects going on including a new born at home  😉

**Comment by stefanbuck** [comment]
@darkred what's your thoughts on the screenshots? Should I include them in the listing? I'm questioning the usefulness of the images. Also the quality is often not that good

**Comment by darkred** [comment]
I agree with you, screenshots are not very useful in the list.
*(I'm sure you could cram short text links to screenshots to the end of each extension description, 
e.g. [screenshot](https://someurl.com), or  screenshots [1](https://someurl.com), [2](https://someurl.com), [3](https://someurl.com), etc )*
but I think it's not worth the trouble).

And a thing I noticed: the '(least)/recently updated' doesn't work.

PS. I'm glad you are positive to my suggestions.

**Comment by stefanbuck** [comment]
I fixed the sorting on that page and pushed a few changes to this repository. 

Apart from building the website, a big chunk of work to removing old and outdated extension which reduces the list from 78 down to 48. I think we can consider this issue as addressed. If you come across this issue and have any suggestions or question please let me know.
