### ISSUE TITLE
Add "Where is it?"

### ISSUE THREAD

**Issue by derimagia** [stefanbuck/awesome-browser-extensions-for-github#15]
Let's you navigate code online:

https://chrome.google.com/webstore/detail/where-is-it/cdgnplmebagbialenimejpokfcodlkdm?hl=en

If I get some time, I'll make a pull request

**Comment by stefanbuck** [comment]
That would be great :+1:

**Comment by derimagia** [comment]
When I went to make a pull request this wan't working for me, sorry for that! I'll need to relook at it if it's working for you
