### ISSUE TITLE
30 entries has been removed from the listing

### ISSUE THREAD

**Issue by darkred** [stefanbuck/awesome-browser-extensions-for-github#174]
Greetings

I've just noticed that 30 entries has been removed from the listing a year ago!

I initially found that the 'Contributors on Github' extension has been removed:
It was added in PR #25 .
It was removed in this commit: https://github.com/stefanbuck/awesome-browser-extensions-for-github/commit/5ecbd68c4f322ae65aefc1eead4b20143485124a a year ago.
In that commit, I also found: 
- 78 occurrences of `###` in the shrinked down `README.md` and 
- only 48 occurrences of `"name"` in the new `data.json`. 

Therefore I found that the following 30 entries were removed with that commit:

<details>
<summary>Missing entries:</summary>

```
asciinema Player for GitHub
Awesome Stars
Builds Tab for GitHub
Contributors on GitHub
Follow GitHub Organization
Follow Me or Not
GitHub AST Viewer
GitHub Categoric
GitHub Diffs
GitHub Markdown Outline Extension
GitHub News Pics
GitHub Omnibar
GitHub Travis Stat
GitHub Turbo PR
GitSense
Gitter Helper
Infinite Commits
News Feed for GitHub
Octo Mate
OctoDraft
OctoEdit
OctoPeek
OctoPreview
OctoTab
OctoTern
Package Hub
Pages2Repo
Review on GitHub
Twitter for GitHub
Where is it?
```
</details>

&nbsp;
PS. Here are the two files of my diff:
[from README.md](https://github.com/stefanbuck/awesome-browser-extensions-for-github/files/6977743/from.README.md.txt)
[from data.json](https://github.com/stefanbuck/awesome-browser-extensions-for-github/files/6977744/from.data.json.txt)

**Comment by stefanbuck** [comment]
Hi, thanks for raising this issue. Back then I spend way too much time removing items from the list which were not working anymore or the feature they added has become part of GitHub itself. https://github.com/DrewML/OctoEdit/issues/28 or https://github.com/wenzhixin/github-news-feed/issues/9 https://github.com/bevacqua/twitter-for-github/issues/12

Please feel free to re-submit extensions that are still working and provide value.

**Comment by darkred** [comment]
I merely thought that those 30 extensions were wrongly removed during the conversion from Markdown to JSON..

I tested them all and they almost all were either abandoned years ago or their pages deleted.
There's only one exception, "Contributors on GitHub" (as mentioned in my OP), for which I just made a PR to re-add.

PS. Thanks once more for all your work all this time.

**Comment by stefanbuck** [comment]
Amazing, thanks for keeping an eye on the repo as well.
