### ISSUE TITLE
Submit new extension: xhub

### ISSUE THREAD

**Issue by nschloe** [stefanbuck/awesome-browser-extensions-for-github#178]
### Name of the browser extension

xhub

### A short description

Extends GitHub pages with math, diagrams, embedded YouTube videos etc.

### Source code repository

https://github.com/nschloe/xhub

### Please select one or more categories

- [ ] Code
- [ ] Codereview
- [ ] Comments
- [ ] IDE
- [X] Miscellaneous
- [ ] Navigation
- [ ] Newsfeed
- [ ] Notifications
- [ ] Profile
- [ ] Pull Request
- [ ] Repository
- [ ] Search
- [ ] Theme

### Chrome web store url

https://chrome.google.com/webstore/detail/xhub/anidddebgkllnnnnjfkmjcaallemhjee

**Comment by stefanbuck** [comment]
xhub looks amazing, well done.

**Comment by stefanbuck** [comment]
Looks like there is an issue with autogenerating the readme.md

**Comment by stefanbuck** [comment]
I fixed the listing, but the stats are not correct. I was aware of this issue and maybe now is the time to fix it 😉

**Comment by stefanbuck** [comment]
Stats have been fixed
