### ISSUE TITLE
Improve list  appearance

### ISSUE THREAD

**Issue by stefanbuck** [stefanbuck/awesome-browser-extensions-for-github#18]
Since the amount of awesome browser extensions for GitHub grows and grows, the overview gets lost. The main issues are the images. They have different sizes and formats which results in a dense, chaotic and not clearly arranged layout. However, I'm afraid even with accurate images it won't get better.

**I'm looking for any ideas on how this could be done any better.**

**Comment by leocaseiro** [comment]
You could follow the [awesome-linux](https://github.com/aleksandar-todorovic/awesome-linux) style.

It comes with a list on top, the click go to the follow ID(description and image) which then, has a link for it project.

**Comment by stefanbuck** [comment]
That's awesome. Thanks for sharing :+1:

**Comment by stefanbuck** [comment]
I added a table of content on top of the list. Thanks again for the hint @leocaseiro
