### ISSUE TITLE
Submit new extension

### ISSUE THREAD

**Issue by Claudiohbsantos** [stefanbuck/awesome-browser-extensions-for-github#181]
### Name of the browser extension

Material Icons for Github

### A short description

Show Material icons for files/folders in repository file viewer. Display the same icons from vscode-material-icon-theme VSCode extension.

### Source code repository

https://github.com/Claudiohbsantos/github-material-icons-extension

### Please select one or more categories

- [ ] Code
- [ ] Codereview
- [ ] Comments
- [ ] IDE
- [ ] Miscellaneous
- [ ] Navigation
- [ ] Newsfeed
- [ ] Notifications
- [ ] Profile
- [ ] Pull Request
- [X] Repository
- [ ] Search
- [X] Theme

### Chrome web store url

https://chrome.google.com/webstore/detail/material-icons-for-github/bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc

### Firefox Addons url

https://addons.mozilla.org/en-US/firefox/addon/material-icons-for-github/

### Microsoft Edge Add-ons url

https://microsoftedge.microsoft.com/addons/detail/material-icons-for-github/khckkdgomkcjjnpgjmdmbceiddlmiolb

**Comment by stefanbuck** [comment]
New icons for GitHub 😍
