### ISSUE TITLE
Submit new extension

### ISSUE THREAD

**Issue by amoghs** [stefanbuck/awesome-browser-extensions-for-github#184]
### Name of the browser extension

New Tab search for GitHub

### A short description

All your issues, PRs, repos and other work documents right in your new tab

### Please select one or more categories

- [ ] Code
- [ ] Codereview
- [ ] Comments
- [ ] IDE
- [ ] Miscellaneous
- [ ] Navigation
- [ ] Newsfeed
- [ ] Notifications
- [ ] Profile
- [ ] Pull Request
- [ ] Repository
- [X] Search
- [ ] Theme

### Chrome web store url

https://chrome.google.com/webstore/detail/eesel-the-new-tab-for-wor/jffaiidojfhflballoapgofphkadiono

### Firefox Addons url

https://addons.mozilla.org/en-US/firefox/addon/eesel/reviews/

**Comment by stefanbuck** [comment]
Thanks for submitting this extension. Strictly speaking this extension is not tailored for GitHub and usually I would reject such a submission (just to be inline with the rules of this awesome list). However, this extension is hitting a nerve. I wrote https://jumpcat.dev/ (kind of similar to eesel, but just for GitHub). Over the last two weeks I was thinking hard how to make Jumpcat work with other websites. It's quite spooky to see eesel now which does a lot of things I had imagined. I just installed it and it works great. I hope you keep the momentum up and adding it to the list will bring you some more visibility. Well done
