### ISSUE TITLE
stefanbuck/github-issue-parser not stefanbuck/github-issue-praser

### ISSUE THREAD

**Issue by mloskot** [stefanbuck/awesome-browser-extensions-for-github#191]
It is [stefanbuck/github-issue-parser](https://github.com/stefanbuck/github-issue-parser), not [stefanbuck/github-issue-praser](https://github.com/stefanbuck/awesome-browser-extensions-for-github/commit/08e50049aaa5782ae51d9d98cb2e119f2c8796fb), isn't it? :)

**Comment by stefanbuck** [comment]
Good catch. However this version is working too, presumably because I had the same typo in the repo name as well which is now causing a redirect. Anyway I'll update the code to avoid confusion.
