### ISSUE TITLE
Submit new extension

### ISSUE THREAD

**Issue by delucis** [stefanbuck/awesome-browser-extensions-for-github#192]
### Name of the browser extension

GitHub to Linear

### A short description

View and create Linear tickets from any GitHub PR or issue.

### Source code repository

https://github.com/delucis/github-to-linear

### Please select one or more categories

- [ ] Code
- [ ] Codereview
- [ ] Comments
- [ ] IDE
- [X] Miscellaneous
- [ ] Navigation
- [ ] Newsfeed
- [ ] Notifications
- [ ] Profile
- [ ] Pull Request
- [ ] Repository
- [ ] Search
- [ ] Theme

### Chrome web store url

https://chrome.google.com/webstore/detail/github-to-linear/hlambaminaoofejligodincejhcbljik

### Firefox Addons url

https://addons.mozilla.org/en-GB/firefox/addon/github-to-linear/

**Comment by stefanbuck** [comment]
Nice extension and sorry for the late response.

**Comment by delucis** [comment]
No worries — thanks for the merge and maintaining this repo!
