### ISSUE TITLE
Submit new extension

### ISSUE THREAD

**Issue by NirmalScaria** [stefanbuck/awesome-browser-extensions-for-github#198]
### Name of the browser extension

Le Git Graph

### A short description

Browser extension to add git graph to GitHub website.

### Source code repository

https://github.com/NirmalScaria/le-git-graph

### Please select one or more categories

- [X] Code
- [ ] Codereview
- [X] Comments
- [ ] IDE
- [ ] Miscellaneous
- [X] Navigation
- [ ] Newsfeed
- [ ] Notifications
- [ ] Profile
- [ ] Pull Request
- [X] Repository
- [ ] Search
- [ ] Theme

### Chrome web store url

https://chrome.google.com/webstore/detail/le-git-graph-commits-grap/joggkdfebigddmaagckekihhfncdobff

### Firefox Addons url

https://addons.mozilla.org/en-US/firefox/addon/le-git-graph-github-git-graph/

**Comment by stefanbuck** [comment]
neat
