### ISSUE TITLE
Render extensions in a grid

### ISSUE THREAD

**Issue by dbkaplun** [stefanbuck/awesome-browser-extensions-for-github#37]
Right now it's hard to discern one extension from another, and each extension is probably too big for the page. Would it be difficult to put each extension in a Pinterest-style 3xN grid so that there are a few extensions per row? I think that may significantly improve usability.

See also https://guides.github.com/features/mastering-markdown/ Ctrl+F "Tables"

**Comment by stefanbuck** [comment]
That's a great idea. Would you like to submit an example PR (with three rows), so we can see how that works out?

**Comment by stefanbuck** [comment]
Solve with #46
