### ISSUE TITLE
Request/Idea

### ISSUE THREAD

**Issue by alecperkey** [stefanbuck/awesome-browser-extensions-for-github#52]
Tooltip/hover div showing repo stats on hover of repo href.

**Comment by stefanbuck** [comment]
In general good idea, but does markdown support tooltips? Second how can we keep those stats up to date?

**Comment by alecperkey** [comment]
Was thinking the starred count, forked count, anything on the public api.
Browser extension doesn't need to use markdown.

**Comment by stefanbuck** [comment]
Now I get it 😉  This is an idea for an extension, not a suggestion for the list. I think https://github.com/Justineo/github-hovercard is what you are looking for.
