### ISSUE TITLE
Add CoderStats link for GitHub Coders

### ISSUE THREAD

**Issue by yaph** [stefanbuck/awesome-browser-extensions-for-github#54]
I have a [Chrome extension](https://github.com/coderstats/cxt_coderstats) / [FireFox add-on](https://github.com/coderstats/fxt_coderstats) that adds a link to the CoderStats page for a GitHub user on the GitHub profile page. Not sure whether this qualifies for your list, as it does not add functionality to GitHub itself, but points to an external site, that shows data from GitHub. If you think it's worth adding, I'm happy to submit a PR.

**Comment by stefanbuck** [comment]
[twitter-for-github](https://github.com/bevacqua/twitter-for-github) does the same and it's also on the list, so go for it 😉
