### ISSUE TITLE
How about adding colorGit?

### ISSUE THREAD

**Issue by taeguk** [stefanbuck/awesome-browser-extensions-for-github#56]
https://github.com/dhdh6190/colorGit

**Comment by stefanbuck** [comment]
Mhhh I think the value of this extension is quite low for a user. It's nice to have the ability to customize the colours, but it's not awesome enough to be on the list, sorry.

**Comment by LestaD** [comment]
## Foo Bar

```js
import { Foo } from 'foo'

Foo.bar().baz()
```

```rust
extern crate foo;

use foo::Foo;

fn main() {
	let bar = Foo::new(foo::i::Bar);
  
  bar.baz();
}
```
