### ISSUE TITLE
[Suggest] Add a few extensions

### ISSUE THREAD

**Issue by yfdyh000** [stefanbuck/awesome-browser-extensions-for-github#73]
I see some extensions are not added, they are listed on https://github.com/sindresorhus/refined-github.

Hide Files on GitHub - Hides dotfiles from the file browser
Octo Linker - Navigate across files and packages
OctoEdit - Markdown syntax highlighting in comments

**Comment by stefanbuck** [comment]
OctoLinker and Hide Files on GitHub are already on the list 😉 Do you mind to send a PR for OctoEdit?
